### ISSUE TITLE
Meta veld 'event_dates_type' meer dan 1 rij in de meta tabel

### ISSUE THREAD

**Issue by mvdhoek1** [OpenWebconcept/plugin-openagenda-base#18]
**Beschrijf de bug**
Wanneer wij 'dates_type' meesturen als 'complex' komen er in de meta tabel 2 rijen namelijk:
'event_dates_type' => 'specific'
'event_dates_type' => 'complex'

Wij sturen 'complex' gewoon als string mee. Daarnaast wanneer wij het evenement nog eens handmatig opslaan worden beide rijen gevuld met de waarde die wij kiezen. Dus ik sla hem op als 'specific' dan staat er in de database:
'event_dates_type' => 'specific'
'event_dates_type' => 'specific'

**Te reproduceren**
Schiet 'specific' of 'complex' in via de API in het veld 'dates_type' (jullie voegen de prefix 'event_' toe)

**Verwacht gedrag**
Dat alleen de gekozen waarde wordt opgeslagen

**Schermafbeeldingen**
![Scherm­afbeelding 2024-04-10 om 15 57 18](https://github.com/OpenWebconcept/plugin-openagenda-base/assets/11852816/8dc84632-10f3-4d77-9551-fe7377025d7e)

**Comment by eyalacato** [comment]
@mvdhoek1 : Ik krijg dit helaas niet gereproduceerd. Kun je misschien de JSON input met mij delen? Dan test ik het daarmee in onze omgeving. Dank!

**Comment by mvdhoek1** [comment]
@eyalacato ik ga dit issue sluiten, schijnbaar gebruikten wij als default `'type' => 'specific'` in de submission data. Ondanks dat dit veld niet 'dates_type' heette pakt jullie plugin deze wel zo op denk ik. Ik heb onze regel weggehaald en nu komt ie netjes binnen. Excuus.

**Comment by eyalacato** [comment]
Aaah oké, goed om te horen dat ie nu netjes binnenkomt!
