### ISSUE TITLE
500 Internal Server Error in API (items endpoint)

### ISSUE THREAD

**Issue by mvdhoek1** [OpenWebconcept/plugin-openagenda-base#19]
**Beschrijf de bug**
500 Internal Server Error

**Te reproduceren**
Ga naar: https://openagenda.ridderkerk.nl/wp-json/owc/openagenda/v1/items/id/184

**Schermafbeeldingen**
<img width="945" alt="Scherm­afbeelding 2024-04-11 om 17 04 52" src="https://github.com/OpenWebconcept/plugin-openagenda-base/assets/11852816/5ed114a2-4470-404c-a55e-0da8ec14c37e">

**Comment by mvdhoek1** [comment]
Ik heb op onze server even het volgende geplaatst:
```
if (! $attachment_meta ) {
	return [];
}
```

**Comment by eyalacato** [comment]
Dit probleem is opgelost in versie 1.0.11. Jouw fix heb ik (iets uitgebreid) opgenomen in de code en daarnaast heb ik nog een aantal extra aanpassingen gedaan, zodat het veld post_thumbnail bij een event en bij een locatie altijd in de output verschijnt en _null_ is als er geen afbeelding is. Hetzelfde geldt voor _images_ en _media_files_ bij een event.
