### ISSUE TITLE
Undefined index 'width' when requesting API

### ISSUE THREAD

**Issue by mvdhoek1** [OpenWebconcept/plugin-openagenda-base#22]
**Beschrijf de bug**
Undefined index 'width', geldt ook voor height en filesize misschien.

**Aanvullende context**
https://github.com/OpenWebconcept/plugin-openagenda-base/blob/main/src/rest_api/class-openagenda-controller.php#L1682

**Comment by eyalacato** [comment]
@mvdhoek1 : ik heb een fix geschreven in versie 1.0.15. Kun je hem aan jullie kant updaten en aangeven of het probleem hiermee verholpen is?

**Comment by mvdhoek1** [comment]
@eyalacato het lijkt goed te gaan, bedankt weer!
