### ISSUE TITLE
Undefined index: location_address

### ISSUE THREAD

**Issue by mvdhoek1** [OpenWebconcept/plugin-openagenda-base#27]
**Beschrijf de bug**
Bepaalde array items worden geleegd en vervolgens weer gebruikt wat een HTTP 500 oplevert.

**Te reproduceren**
Open het items endpoint (API)

**Schermafbeeldingen**
1.
![openagenda_api_500](https://github.com/OpenWebconcept/plugin-openagenda-base/assets/11852816/828e2e46-16eb-4092-891f-7c9967b33473)

2.
<img width="761" alt="Scherm­afbeelding 2024-06-24 om 08 46 12" src="https://github.com/OpenWebconcept/plugin-openagenda-base/assets/11852816/425d766f-91ce-41d9-a40c-ad2aaf9a49a9">

**Comment by eyalacato** [comment]
@mvdhoek1 : Ook hier kijk ik woensdag even naar voor je.

**Comment by mvdhoek1** [comment]
Thanks @eyalacato!

**Comment by eyalacato** [comment]
Hi @mvdhoek1 , Dit issue is opgelost in versie 1.1.4
