### ISSUE TITLE
Bevragen van https://nominatim.openstreetmap.org zorgt voor een trage API.

### ISSUE THREAD

**Issue by mvdhoek1** [OpenWebconcept/plugin-openagenda-base#28]
**Beschrijf de bug/enhancement**
Niet persé een bug, meer een verbetering.
API (/wp-json/owc/openagenda/v1/items) is traag door het bevragen van `https://nominatim.openstreetmap.org` per item.

**Te reproduceren**
1. Open: https://openagenda.ridderkerk.nl/wp-json/owc/openagenda/v1/items?per_page=10
2. Open daarna: https://openagenda.ridderkerk.nl/wp-json/owc/openagenda/v1/items?per_page=1
3. Zie het verschil in laadtijd.

**Verwacht gedrag**
Wellicht vooraf checken of een adres is gewijzigd en alleen dan een request maken naar `https://nominatim.openstreetmap.org`

**Comment by mvdhoek1** [comment]
Ik heb de versie verlaagd op de Ridderkerk omgeving omdat detail pagina's te langzaam werden. De stappen om te reproduceren zijn niet meer van toepassing.

**Comment by eyalacato** [comment]
Hi @mvdhoek1 , ik kijk hier woensdag even naar voor je. Ik zal het je laten weten als het opgelost is en er een nieuwe versie beschikbaar is.

**Comment by mvdhoek1** [comment]
Helemaal goed @eyalacato!

**Comment by eyalacato** [comment]
Hi @mvdhoek1 , Dit issue is opgelost in versie 1.1.4
