### ISSUE TITLE
Toevoegen van afbeelding bij evenement geeft een fout

### ISSUE THREAD

**Issue by mvdhoek1** [OpenWebconcept/plugin-openagenda-base#6]
**Beschrijf de bug**
DEBUG: ftp_fput() expects parameter 1 to be resource, null given

/data/www/bar/openagenda.ridderkerk.nl/releases/7/htdocs/wp/wp-admin/includes/class-wp-filesystem-ftpext.php Line 212

**Te reproduceren**
Schiet een base 64 encoded afbeelding in via de API.

**Comment by eyalacato** [comment]
We zullen een check inbouwen die checkt of er een bestand opgeslagen kan worden op de server of niet. Als dit niet lukt, dan zullen we een foutmelding teruggeven. Iets in de richting van onderstaand.

if ( false === $wp_filesystem->put_contents( $filepath, $file_contents ) ) {
    throw new Exception( "Can't create file: $filepath" );
}

**Comment by mvdhoek1** [comment]
Top!

**Comment by eyalacato** [comment]
@mvdhoek1 : dit is opgelost in versie 1.0.6. Je zult nu een foutmelding krijgen als je een bestand probeert op te slaan terwijl er geen juiste schrijfrechten zijn op de server.
